import { rateByCode } from './marketRates';

type Localized = { zh: string; en: string };
type Reference = { name: Localized; source: string; value?: string; date?: string; meta?: Localized };
type MarketRates = { money: Reference; short: Reference; long: Reference; note?: Localized };
const name = (zh: string, en: string): Localized => ({ zh, en });
const ref = (zh: string, en: string, source: string, value?: string, date?: string): Reference => ({ name: name(zh, en), source, value, date });

// Values are deliberately sparse: a dated, verified official snapshot is better than a stale "live" quote.
const markets: Record<string, MarketRates> = {
  HK: { money: ref('港元银行同业拆息 HIBOR', 'HKD interbank offered rate (HIBOR)', 'https://apidocs.hkma.gov.hk/documentation/market-data-and-statistics/monthly-statistical-bulletin/er-ir/hk-interbank-ir-daily/'), short: ref('外汇基金票据收益率', 'Exchange Fund Bill yield', 'https://apidocs.hkma.gov.hk/documentation/market-data-and-statistics/monthly-statistical-bulletin/efbn/efbn-yield-daily/'), long: ref('10 年期外汇基金债券收益率', '10-year Exchange Fund Note yield', 'https://apidocs.hkma.gov.hk/documentation/market-data-and-statistics/monthly-statistical-bulletin/efbn/efbn-yield-daily/') },
  MY: { money: ref('隔夜货币市场利率 MYOR', 'Malaysia Overnight Rate (MYOR)', 'https://financialmarkets.bnm.gov.my/data-download-myor', '2.75%', '2026-09-21'), short: ref('3–6 个月国库券收益率', '3–6-month Treasury Bill yield', 'https://www.bnm.gov.my/government-securities-yield'), long: ref('10 年期马来西亚政府债 MGS', '10-year Malaysian Government Securities', 'https://financialmarkets.bnm.gov.my/benchmark-yields?form=MG0AV3', '3.90%', '2026-09-22') },
  US: { money: ref('有担保隔夜融资利率 SOFR', 'Secured Overnight Financing Rate (SOFR)', 'https://www.newyorkfed.org/markets/reference-rates/sofr'), short: ref('6 个月美国国库券收益率', '6-month US Treasury yield', 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?field_tdr_date_value_month=202609&type=daily_treasury_yield_curve', '4.26%', '2026-09-22'), long: ref('10 年期美国国债收益率', '10-year US Treasury yield', 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?field_tdr_date_value_month=202609&type=daily_treasury_yield_curve', '4.96%', '2026-09-22') },
  ID: { money: ref('印尼隔夜指数利率 IndONIA', 'Indonesia Overnight Index Average (IndONIA)', 'https://www.bi.go.id/id/fungsi-utama/moneter/indonia-jibor/Default.aspx'), short: ref('短期国库券 SPN 拍卖收益率', 'SPN Treasury Bill auction yield', 'https://djppr.kemenkeu.go.id/produkdanlayanan'), long: ref('10 年期政府债 SUN 收益率', '10-year government bond (SUN) yield', 'https://djppr.kemenkeu.go.id/produkdanlayanan') },
  MX: { money: ref('隔夜融资利率 TIIE de Fondeo', 'Overnight TIIE funding rate', 'https://www.banxico.org.mx/SieInternet/consultarDirectorioInternetAction.do?accion=consultarCuadroAnalitico&idCuadro=CA766&locale=en&sector=18'), short: ref('182 天 CETES 国库券收益率', '182-day CETES yield', 'https://www.banxico.org.mx/SieInternet/consultarDirectorioInternetAction.do?accion=consultarCuadro&idCuadro=CF300&locale=en'), long: ref('10 年期政府债 Bonos 收益率', '10-year Bonos yield', 'https://www.banxico.org.mx/SieInternet/consultarDirectorioInternetAction.do?accion=consultarCuadro&idCuadro=CF300&locale=en') },
  AE: { money: ref('阿联酋银行同业拆息 EIBOR', 'Emirates Interbank Offered Rate (EIBOR)', 'https://centralbank.ae/en/forex-eibor/'), short: ref('迪拉姆国库券／政府债拍卖', 'AED Treasury Bill / bond auctions', 'https://mof.gov.ae/en/public-finance/public-debt/issuance-programme/'), long: ref('迪拉姆长期国债／伊斯兰债', 'Longer AED Treasury Bonds / Sukuk', 'https://mof.gov.ae/en/public-finance/public-debt/issuance-programme/'), note: name('按实际发行期限比较；不强行套用 10 年期。', 'Compare actual issue maturities; do not assume a standing 10-year benchmark.') },
  SG: { money: ref('3 个月复合 SORA', '3-month compounded SORA', 'https://eservices.mas.gov.sg/Statistics/dir/DomesticInterestRates.aspx'), short: ref('6 个月新加坡国库券收益率', '6-month Singapore Treasury Bill yield', 'https://eservices.mas.gov.sg/Statistics/fdanet/SgsBenchmarkIssuePrices.aspx', '1.68%', '2026-09-22'), long: ref('10 年期新加坡政府债收益率', '10-year Singapore Government Bond yield', 'https://eservices.mas.gov.sg/Statistics/fdanet/SgsBenchmarkIssuePrices.aspx', '2.41%', '2026-09-22'), note: name('新加坡以汇率为货币政策核心，没有统一的“央行基准贷款利率”；SORA 是更实用的新元市场参考。', 'Singapore conducts monetary policy through the exchange rate, not a single policy lending rate; SORA is the practical SGD market benchmark.') },
  TH: { money: ref('泰铢隔夜回购利率 THOR', 'Thai Overnight Repurchase Rate (THOR)', 'https://app.bot.or.th/BTWS_STAT/statistics/BOTWEBSTAT.aspx?language=Eng&reportID=945'), short: ref('182 天泰国国库券收益率', '182-day Thai Treasury Bill yield', 'https://pdmo.go.th/en/bond-government_bond-treasury_bills'), long: ref('10 年期泰国政府债收益率', '10-year Thai Government Bond yield', 'https://www.pdmo.go.th/en/bond-government_bond-gov_bond') },
  SA: { money: ref('沙特银行同业拆息 SAIBOR', 'Saudi interbank offered rate (SAIBOR)', 'https://www.sama.gov.sa/en-US/EconomicReports/Pages/MonthlyStatistics.aspx'), short: ref('短期政府伊斯兰债拍卖', 'Shorter government sukuk auctions', 'https://ndmc.gov.sa/en/-local-sukuk-issuance-program-in-saudi-riyal'), long: ref('长期政府伊斯兰债收益率', 'Longer government sukuk yield', 'https://ndmc.gov.sa/en/-local-sukuk-issuance-program-in-saudi-riyal'), note: name('按发行期次和剩余期限查报价。', 'Check the issue and remaining maturity before comparing yields.') },
  DE: { money: ref('欧元短期利率 €STR', 'Euro short-term rate (€STR)', 'https://www.ecb.europa.eu/stats/financial_markets_and_interest_rates/euro_short-term_rate/html/eurostr_qa.en.html'), short: ref('12 个月德国联邦国库券 Bubill', '12-month German Bubill yield', 'https://www.deutsche-finanzagentur.de/en/federal-securities/issuances/issuance-results'), long: ref('10 年期德国联邦债 Bund', '10-year German Bund yield', 'https://www.bundesbank.de/en/statistics/money-and-capital-markets/interest-rates-and-yields/daily-yields-of-current-federal-securities-772220') },
  JP: { money: ref('日元隔夜无担保拆借利率', 'Uncollateralised overnight call rate', 'https://www.boj.or.jp/en/statistics/market/short/mutan/index.htm'), short: ref('6 个月日本国库贴现券', '6-month Japanese Treasury Discount Bill', 'https://www.mof.go.jp/english/policy/jgbs/auction/past_auction_results/index.html'), long: ref('10 年期日本国债 JGB', '10-year Japanese Government Bond', 'https://www.mof.go.jp/english/policy/jgbs/auction/past_auction_results/index.html') },
  KR: { money: ref('韩元无风险参考利率 KOFR', 'Korea Overnight Financing Repo Rate (KOFR)', 'https://www.bok.or.kr/eng/main/contents.do?menuNo=400399'), short: ref('2 年期韩国国债 KTB', '2-year Korean Treasury Bond', 'https://ktb.moef.go.kr/'), long: ref('10 年期韩国国债 KTB', '10-year Korean Treasury Bond', 'https://ktb.moef.go.kr/'), note: name('短端采用 2 年期国债，不与 6 个月国库券直接横比。', 'Short-tenor proxy is a 2-year bond, not directly comparable with a 6-month bill.') },
  PH: { money: ref('菲律宾央行公开市场利率', 'BSP money-market reference', 'https://www.bsp.gov.ph/Statistics/sdds/sdds.aspx'), short: ref('182 天菲律宾国库券拍卖', '182-day Philippine Treasury Bill auction', 'https://www.treasury.gov.ph/?cat=14'), long: ref('长期菲律宾政府债拍卖', 'Longer Philippine Treasury Bond auction', 'https://www.treasury.gov.ph/?cat=14'), note: name('长期券以当期实际发行期限为准。', 'Use the actual tenor of the available long-term issue.') },
  AU: { money: ref('澳元隔夜市场利率', 'Australian overnight money-market rate', 'https://www.rba.gov.au/statistics/tables/'), short: ref('6 个月澳大利亚国库券', '6-month Australian Treasury Note', 'https://www.rba.gov.au/statistics/tables/'), long: ref('10 年期澳大利亚政府债', '10-year Australian Government Bond', 'https://www.rba.gov.au/statistics/tables/') },
  RU: { money: ref('卢布隔夜利率 RUONIA', 'Ruble Overnight Index Average (RUONIA)', 'https://www.cbr.ru/eng/hd_base/ruonia/'), short: ref('短期 OFZ 国债收益率曲线', 'Short OFZ government-bond curve', 'https://www.cbr.ru/eng/hd_base/zcyc_params/'), long: ref('10 年期 OFZ 国债收益率曲线', '10-year OFZ government-bond curve', 'https://www.cbr.ru/eng/hd_base/zcyc_params/'), note: name('另须先核制裁、清算、保险及实际可交易性。', 'Sanctions, settlement, insurance and tradability must be checked first.') },
  CA: { money: ref('加元隔夜回购基准 CORRA', 'Canadian Overnight Repo Rate Average (CORRA)', 'https://www.bankofcanada.ca/rates/interest-rates/corra/'), short: ref('6 个月加拿大国库券拍卖收益率', '6-month Canadian Treasury Bill auction yield', 'https://www.bankofcanada.ca/rates/interest-rates/t-bill-yields/', '2.59%', '2026-09-22'), long: ref('10 年期加拿大政府债基准收益率', '10-year Canadian government bond benchmark', 'https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/', '3.84%', '2026-09-21') },
  GB: { money: ref('英镑隔夜指数利率 SONIA', 'Sterling Overnight Index Average (SONIA)', 'https://www.bankofengland.co.uk/markets/sonia-benchmark'), short: ref('英国短期国库券拍卖收益率', 'UK Treasury Bill auction yield', 'https://www.dmo.gov.uk/data/treasury-bills/'), long: ref('10 年期英国国债 Gilt 收益率', '10-year UK Gilt yield', 'https://www.bankofengland.co.uk/statistics/yield-curves') },
  BR: { money: ref('巴西银行间隔夜利率 CDI', 'Brazilian interbank overnight rate (CDI)', 'https://www.bcb.gov.br/en/financialstability/selic'), short: ref('短期巴西国债发行收益率', 'Shorter Brazilian government-security yield', 'https://www.tesourotransparente.gov.br/ckan/dataset/taxas-dos-titulos-ofertados-pelo-tesouro-direto'), long: ref('长期巴西国债发行收益率', 'Longer Brazilian government-security yield', 'https://www.tesourotransparente.gov.br/ckan/dataset/taxas-dos-titulos-ofertados-pelo-tesouro-direto'), note: name('巴西零售国债按具体品种和到期日比较，不能把不同指数化债券当作同一 10 年期。', 'Compare the actual product and maturity; indexed retail bonds are not interchangeable with a single 10-year yield.') },
};

export function CapitalMarketRates({ code, locale }: { code: string; locale: 'zh' | 'en' }) {
  const item = markets[code];
  const policy = rateByCode[code];
  if (!item || !policy) return null;
  const zh = locale === 'zh';
  const entries: { heading: Localized; data: Reference }[] = [
    { heading: name('政策利率 / 货币框架', 'Policy / monetary framework'), data: policy.value === '—' ? { ...ref(policy.zh, policy.en, policy.source, zh ? '无单一利率' : 'No single rate'), meta: name('汇率主导型货币政策', 'Exchange-rate-centred policy') } : ref(policy.zh, policy.en, policy.source, policy.value, policy.date) },
    { heading: name('市场短期利率', 'Short-term market rate'), data: item.money },
    { heading: name('短期国库券 / 政府债', 'Short sovereign security'), data: item.short },
    { heading: name('长期国债收益率', 'Long sovereign yield'), data: item.long },
  ];
  return <section className="capital-rates" aria-label={zh ? '资金与债券利率' : 'Funding and sovereign yields'}>
    <div className="capital-rates-head"><div><span>{zh ? '资金与债券' : 'CAPITAL & RATES'}</span><h4>{zh ? '看利率，也要看期限与融资成本。' : 'Read the rate, tenor and actual cost of funding.'}</h4></div><p>{zh ? '同一市场，四种数字回答四个不同问题。' : 'Four different measures answer four different questions.'}</p></div>
    <div className="capital-rates-grid">{entries.map(({ heading, data }) => <div className="capital-rate" key={heading.en}><span className="capital-rate-label">{heading[locale]}</span><strong>{data.value || (zh ? '查当期报价' : 'Check current quote')}</strong><span className="capital-rate-name">{data.name[locale]}</span><span className="capital-rate-meta">{data.meta ? data.meta[locale] : data.date ? (zh ? `官方快照 · ${data.date}` : `Official snapshot · ${data.date}`) : (zh ? '未固定展示实时数值' : 'No live value embedded')}</span><a href={data.source} target="_blank" rel="noopener noreferrer">{zh ? '官方数据 ↗' : 'Official data ↗'}</a></div>)}</div>
    {item.note && <p className="capital-rates-note">{item.note[locale]}</p>}
    <div className="capital-rates-loan"><b>{zh ? '企业实际借款成本' : 'ACTUAL BUSINESS BORROWING COST'}</b><span>{zh ? '不能由国债收益率直接推算。须向当地银行分别询价：借款主体、币种、期限、信用利差、担保、手续费与汇率对冲。' : 'Not the sovereign yield. Request local bank quotes by borrowing entity, currency, tenor, credit spread, collateral, fees and FX hedge.'}</span></div>
    <p className="capital-rates-disclaimer">{zh ? '利率为不同日期的静态官方快照或查询入口，非实时行情；拍卖、二级市场、曲线估值及不同期限不可直接横向排序。投资或融资前重查。' : 'Figures are dated official snapshots or lookup links, not live prices. Auction, secondary-market and model-curve yields, and different tenors, are not directly comparable. Recheck before investing or borrowing.'}</p>
  </section>;
}
