'use client';

import { useState } from 'react';
import { ArrowDown, ArrowUpRight, Bot, Check, CircleDot, Database, Globe2, Languages, Network, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { StrategyGlobe } from './StrategyGlobe';
import { CapitalMarketRates } from './CapitalMarketRates';
import { PharmacyLaunchGuide } from './PharmacyLaunchGuide';
import { MarketIntelligence } from './MarketIntelligence';
import { CriticalPathAlerts } from './CriticalPathAlerts';
import { ExecutionWorkbench } from './ExecutionWorkbench';
import { europeanMarkets } from './europeMarkets';

const markets = [
  ['Hong Kong, China', 'HK', 'Global hub · Continuous build', 'First overseas subsidiary & global launch hub', 'S2B2C operations + investment + partnerships', 'Jiajia Health’s first overseas company: the investment, partnership and coordination base from which the network expands into priority global markets.', { tax: 'Profits tax: 8.25% on the first HK$2m, then 16.5%; no VAT / GST; online shops follow the same source-of-profit rules', population: '7.52m', gdp: 'US$408.4bn', fx: 'US$1 ≈ HK$7.84', language: 'Cantonese · Mandarin · English', logistics: 'Global air and sea transshipment; free port with a compact last mile' }],
  ['Malaysia', 'MY', 'Launch market · Months 0—6', 'End-to-end low-cost pilot', 'E2C + selected B2C + foundational B2B', 'Validate platform, payment, logistics, content and merchant operations in one controlled market.', { tax: 'Corporate tax generally 24%; 10% tax on imported online goods ≤ MYR500, with registration above MYR500,000 annual sales; local SST varies by category', population: '35.56m', gdp: 'US$422.2bn', fx: 'US$1 ≈ MYR 4.07', language: 'Malay · English · Chinese · Tamil', logistics: 'Port Klang / Tanjung Pelepas + Kuala Lumpur air; East Malaysia needs a separate fulfilment plan' }],
  ['United States', 'US', 'Launch market · Months 0—6', 'High-value content and brand pilot', 'E2C + selected B2C', 'Validate expert-led content and trust conversion in a mature consumer market.', { tax: 'Federal corporate income tax 21%; sales tax varies by state and delivery address; marketplace collection and economic-nexus thresholds are state-specific', population: '340.00m', gdp: 'US$29.30tn', fx: 'Local currency USD · 1.00', language: 'Primarily English · Spanish widely used', logistics: 'Mature parcel and 3PL network; link interstate distance, tax and warehouse planning' }],
  ['Indonesia', 'ID', 'Second wave · Months 7—12', 'Regional channel pilot', 'S2B2C + B2C + E2C', 'Connect local distributors and retail endpoints with China and global supply.', { tax: 'Corporate income tax 22%; effective VAT generally 11%; designated marketplaces withhold 0.5% of domestic merchants’ gross turnover', population: '283.49m', gdp: 'US$1.40tn', fx: 'US$1 ≈ IDR 17,562', language: 'Indonesian · regional languages', logistics: 'Archipelago network; Jakarta / Surabaya gateways with higher inter-island last-mile costs' }],
  ['Mexico', 'MX', 'Second wave · Months 7—12', 'Latin America replication pilot', 'B2B + B2C + E2C', 'Build the Spanish-language and fulfilment template for further regional expansion.', { tax: 'Corporate income tax 30%; VAT 16%; platforms withhold 1% income tax on individual sellers’ goods or services, plus applicable VAT withholding', population: '130.86m', gdp: 'US$1.83tn', fx: 'US$1 ≈ MXN 16.97', language: 'Spanish · Indigenous languages', logistics: 'US border roads + Pacific ports; assess security and last-mile timing by state' }],
  ['United Arab Emirates', 'AE', 'Replication · Months 13—18', 'Middle East business node', 'B2B / E2C first, then B2C', 'Build institutional and brand connections before expanding consumer operations.', { tax: 'Corporate tax: 0% up to AED375,000 taxable income, then 9%; VAT 5%, with a AED375,000 mandatory registration threshold for resident businesses', population: '10.99m', gdp: 'US$552.3bn', fx: 'US$1 = AED 3.6725', language: 'Arabic · English widely used', logistics: 'Jebel Ali + Dubai / Abu Dhabi air cargo; strong GCC re-export hub' }],
  ['Singapore', 'SG', 'Regional node · Under review', 'Southeast Asia connection point', 'E2C + B2B partnerships', 'Connect experts, brands, institutions and capital; any pharmacy or medicine sales require separate product, licensing and e-pharmacy checks.', { tax: 'Corporate income tax 17%; standard GST 9%, subject to registration, cross-border and exemption rules', population: '6.11m', gdp: 'US$603.9bn', fx: 'US$1 ≈ SGD1.27', language: 'English · Chinese · Malay · Tamil', logistics: 'Changi air and sea hub; check medicine import and cold-chain requirements' }],
  ['Thailand', 'TH', 'Future opportunity · Under review', 'Local channel watchlist', 'B2B partnerships + localised E2C', 'Review pharmacy licences, product registration and Thai-language content before building local distribution.', { tax: 'Standard corporate income tax 20%; current VAT 7%, subject to registration and transaction rules', population: '71.62m', gdp: 'US$577.0bn', fx: 'US$1 ≈ THB33.27', language: 'Thai · English for business', logistics: 'Bangkok air and port gateways; assess provincial and cold-chain costs' }],
  ['Saudi Arabia', 'SA', 'Future opportunity · Under review', 'Gulf expansion market', 'B2B institutional partnerships first', 'Study institution demand, product registration and local fulfilment through the UAE node before retail investment.', { tax: 'Standard VAT 15%; income tax and zakat depend on ownership and taxable activity', population: '36.97m', gdp: 'US$1.28tn', fx: 'US$1 = SAR3.75 (official peg)', language: 'Arabic · English for business', logistics: 'Plan Riyadh, Jeddah and Dammam separately; review imports and regional delivery' }],
  ['Germany', 'DE', 'Future opportunity · Under review', 'European market-entry watchlist', 'E2C content + compliant supply partners', 'Review EU and German online-medicine rules, pharmacy registers, privacy and German content before entering Europe.', { tax: 'Standard VAT 19%, with 7% for eligible goods; corporate income and local trade tax separately', population: '83.49m', gdp: 'US$5.05tn', fx: 'US$1 ≈ EUR0.87', language: 'German · English for business', logistics: 'Mature European parcel network; cross-border medicines depend on destination rules' }],
  ...europeanMarkets.map((item) => [item.name.en, item.code, 'European research · Outside 18-month commitment', item.role.en, item.model.en, item.detail.en, item.facts.en] as const),
  ['Japan', 'JP', 'Research watchlist · Outside 18-month commitment', 'High-standard Northeast Asia market', 'E2C + licensed B2B channels', 'Find a licensed local partner and separately assess device classification, medicine supply and medical-facility approvals.', { tax: 'Standard consumption tax 10%; national and local corporate taxes depend on entity and location', population: '123.37m', gdp: 'US$4.44tn', fx: 'US$1 ≈ JPY157.18', language: 'Japanese', logistics: 'Mature Tokyo / Osaka air and sea routes; check medical imports and cold chain' }],
  ['South Korea', 'KR', 'Research watchlist · Outside 18-month commitment', 'Northeast Asia digital-health watchlist', 'E2C + B2B partnerships', 'Validate Korean content, MFDS market authorisation and licensed distribution; a general online shop is not a medicine-sales licence.', { tax: 'Standard VAT 10%; tiered corporate and local income taxes require entity-level checks', population: '51.68m', gdp: 'US$1.87tn', fx: 'US$1 ≈ KRW1,356.15', language: 'Korean', logistics: 'Seoul / Incheon network is efficient; healthcare imports and local delivery need review' }],
  ['Philippines', 'PH', 'Research watchlist · Outside 18-month commitment', 'Archipelago healthcare market', 'B2B + locally partnered B2C', 'Test FDA drugstore and device-retailer licences, health-facility permits and inter-island fulfilment costs.', { tax: 'Standard VAT 12%; corporate income and platform withholding depend on entity and transaction', population: '116.79m', gdp: 'US$487.1bn', fx: 'US$1 ≈ PHP62.46', language: 'Filipino · English', logistics: 'Manila gateway; inter-island shipping, cold chain and remote delivery need separate costing' }],
  ['Australia', 'AU', 'Research watchlist · Outside 18-month commitment', 'Transparent but demanding regulatory market', 'E2C + compliant device B2B', 'Devices generally need an Australian sponsor and ARTG inclusion; pharmacy ownership and facilities also require state or territory review.', { tax: 'Standard GST 10%; company tax usually 25% or 30% depending on eligibility', population: '27.61m', gdp: 'US$1.80tn', fx: 'US$1 ≈ AUD1.41', language: 'English · multilingual communities', logistics: 'Sydney / Melbourne ports and airports; long distances and cold chain add domestic cost' }],
  ['Russia', 'RU', 'Research watchlist · Outside 18-month commitment', 'Sanctions and settlement review first', 'Cautious B2B assessment', 'Check product registration, remote medicine-sales permits, sanctions screening, banks and shipping before any commercial commitment.', { tax: 'VAT and profit tax depend on entity and transaction; cross-border settlement and sanctions review come first', population: '143.51m', gdp: 'US$2.56tn', fx: 'US$1 ≈ RUB84.07', language: 'Russian', logistics: 'Rail and Far East ports may be assessed; carriers, insurers, banks and sanctions are gating issues' }],
  ['Canada', 'CA', 'Research watchlist · Outside 18-month commitment', 'North American Chinese-community market', 'E2C + licensed channel partners', 'Assess Health Canada product authorisation and province/territory-specific pharmacy and medical-facility rules.', { tax: 'Federal plus provincial corporate taxes; GST/HST/PST depend on province and product', population: '41.65m', gdp: 'US$2.32tn', fx: 'US$1 ≈ CAD1.40', language: 'English · French', logistics: 'Toronto / Vancouver gateways; distances, provinces and cold chain affect fulfilment' }],
  ['United Kingdom', 'GB', 'Research watchlist · Outside 18-month commitment', 'English-language content and partnership market', 'E2C + licensed pharmacy partnerships', 'Separate MHRA product rules, GPhC pharmacy registration and healthcare-service facility registration.', { tax: 'Standard VAT 20%; corporation-tax band depends on profit and entity', population: '69.49m', gdp: 'US$4.00tn', fx: 'US$1 ≈ GBP0.748', language: 'English', logistics: 'London air and national parcel networks; medicine cross-border movement needs separate review' }],
  ['Brazil', 'BR', 'Research watchlist · Outside 18-month commitment', 'Second Latin America replication watchlist', 'B2B + Portuguese E2C', 'Do not copy Mexico’s model unaltered: validate ANVISA approvals, pharmacy authorisation, taxes by state and local delivery.', { tax: 'Tax reform is in transition; turnover and corporate taxes depend on product, state and entity', population: '212.81m', gdp: 'US$2.28tn', fx: 'US$1 ≈ BRL5.12', language: 'Portuguese', logistics: 'São Paulo gateway; large territory, state-level taxes and last mile add complexity' }],
];
const stages = [
  ['Stage 0', '0—2 months', 'Set direction, build the core', 'Gate 0', 'Scope is ready for development', ['Hong Kong overseas company and investment hub', 'Country × category compliance matrix', 'Expert verification and review standard', 'Core product prototype']],
  ['Stage 1', '3—6 months', 'Launch the MVP', 'Gate 1', 'Prove the platform can operate', ['Malaysia transaction path', 'US E2C content launch', 'Supplier profiles and inquiries', 'AI localisation workflow']],
  ['Stage 2', '7—12 months', 'Validate the commercial loop', 'Gate 2', 'Prove the model closes the loop', ['Launch Indonesia and Mexico', 'Expert profiles and Q&A', 'Knowledge and buying assistant', 'Partner and fulfilment templates']],
  ['Stage 3', '13—18 months', 'Replicate and platformise', 'Gate 3', 'Prove the model can replicate', ['Replicate into the UAE', 'Country configuration templates', 'Merchant self-onboarding', 'AI compliance and procurement']],
];

export default function EnglishStrategy() {
  const [activeMarket, setActiveMarket] = useState(0);
  const market = markets[activeMarket];
  return <main lang="en">
    <section className="hero" id="top"><div className="hero-image" aria-hidden="true"/><div className="hero-shade" aria-hidden="true"/>
      <nav className="nav-shell" aria-label="Main navigation"><a className="brand" href="#top"><span className="brand-mark"><Network size={17}/></span><span>JIAJIA HEALTH</span></a><div className="nav-links"><a href="#top">S2B2C</a><a href="#globe">Global Globe</a><a href="#foundation">Product Base</a><a href="#markets">Market Entry</a><a href={`${import.meta.env.BASE_URL}economy/?lang=en`}>Economy & Rates</a><a href="#alerts">Approval Alerts</a><a href="#pharmacy-guide">Launch Guide</a></div><a className="nav-action" href="?lang=zh">中文 <ArrowUpRight size={15}/></a></nav>
      <div className="hero-content"><div className="eyebrow"><Globe2 size={15}/> GLOBAL HEALTH PLATFORM</div><h1 className="hero-system-title"><strong className="hero-s2b2c">S2B2C</strong><span>Global Health Platform</span></h1><div className="hero-business-tree" aria-label="S2B2C platform consists of B2B, B2C and E2C"><article><strong>B2B</strong><span>Supply & channels</span></article><article><strong>B2C</strong><span>Consumer commerce</span></article><article><strong>E2C</strong><span>Experts & trust</span></article></div><p>Starting from our first overseas subsidiary in Hong Kong, China, we connect capital, brands, experts and supply chains, then replicate the S2B2C model across priority markets.</p><div className="hero-actions"><a className="primary-action" href="#globe">View global footprint <ArrowDown size={16}/></a><span className="hero-note">HONG KONG LAUNCH HUB<br/>INVESTING GLOBALLY</span><a className="execution-hero-link" href="#execution">Open execution checklist <ArrowUpRight size={15}/></a></div></div><div className="hero-index"><span>01</span><i/><span>08</span></div>
    </section>
    <StrategyGlobe locale="en" onOpenMarket={(code) => setActiveMarket(Math.max(0, markets.findIndex((item) => item[1] === code)))} />
    <section className="foundation-section" id="foundation"><div className="foundation-copy"><div className="section-kicker">EXISTING PRODUCT BASE</div><h2>Globalising proven capabilities,<br/>not starting from zero.</h2><p>Current test materials already cover a B2B pharmaceutical marketplace, B2C mini-program and app, and the E2C Academy. The international platform turns these into a shared global core, then configures language, payment, logistics and compliance by market.</p><div className="foundation-status"><span>CURRENT STATUS</span><strong>Test prototypes · Pre-launch</strong></div><div className="foundation-path"><article><span>01</span><div><h3>B2B marketplace</h3><p>Supplier credentials, product search, MOQs and tiered pricing, procurement, order fulfilment, settlement and role-based permissions.</p></div></article><article><span>02</span><div><h3>B2C consumer channel</h3><p>Mini-program and app journeys for courses, books, membership, orders and payment—from discovery to purchase.</p></div></article><article><span>03</span><div><h3>E2C Academy</h3><p>Expert, institution and pharmaceutical-company onboarding, compliant learning content, public courses and human review.</p></div></article></div><a className="foundation-link" href="#markets">View the global market-entry sequence <ArrowUpRight size={16}/></a></div><div className="foundation-visual"><div className="prototype-frame"><iframe src={`${import.meta.env.BASE_URL}app-front.html`} title="Full interactive Jiajia Health Academy prototype" loading="lazy" sandbox="allow-scripts allow-forms allow-same-origin"/></div></div></section>
    <section className="trust-section"><div className="trust-copy"><div className="section-kicker light">FIRST GROWTH ENGINE</div><h2>E2C is not a content channel.<br/>It is trust infrastructure.</h2><p>Users first resolve “what should I trust?” before deciding “what should I buy?” Professional credibility takes priority over short-term GMV.</p><ul className="principles"><li><ShieldCheck/>Traceable credentials and editorial review</li><li><Languages/>Global content master, local compliance</li><li><Sparkles/>One source, multilingual distribution</li></ul></div><div className="trust-ladder">{[['01','Trusted knowledge base','Articles, video, FAQs and topic pages'],['02','Expert network','Verified profiles, Q&A and interviews'],['03','Knowledge to commerce','Product links, AI guidance and procurement content']].map(([n,t,d])=><div className="ladder-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight/></div>)}</div></section>
    <section className="markets-section" id="markets"><div className="section-topline"><div><div className="section-kicker">MARKET ENTRY</div><h2>Launch from Hong Kong.<br/>Prove two pilots. Replicate by region.</h2></div><p>Build the overseas company, investment platform and global coordination hub in Hong Kong, then validate Malaysia and the United States before wider expansion. Additional markets are research watchlist entries, not commitments in the 18-month roadmap.</p></div><a className="market-economy-link" href={`${import.meta.env.BASE_URL}economy/?lang=en`}>Country macro: yields, public debt and external risk <ArrowUpRight size={16}/></a><div className="market-workspace"><div className="market-list" role="tablist">{markets.map((m,i)=><button key={m[1] as string} role="tab" aria-selected={activeMarket===i} className={activeMarket===i?'active':''} onClick={()=>setActiveMarket(i)}><b>{m[0] as string}</b><small>{m[1] as string}</small></button>)}</div><div className="market-detail" role="tabpanel"><div className="market-mapmark"><Globe2/><span>{market[1] as string}</span></div><div className="market-phase">{market[2] as string}</div><h3>{market[3] as string}</h3><div className="market-model">{market[4] as string}</div><p>{market[5] as string}</p><div className="proof-list"><span><Check/>Local compliance</span><span><Check/>Content workflow</span><span><Check/>Commercial evidence</span></div><div className="market-facts" aria-label={`${market[0]} market data`}>{Object.entries(market[6] as Record<string,string>).map(([key,value])=><div key={key}><span>{{tax:'E-commerce taxes',population:'Population',gdp:'Nominal GDP',fx:'USD exchange',language:'Languages',logistics:'Logistics'}[key]}</span><strong>{value}</strong></div>)}</div><p className="market-source">Population &amp; GDP: <a href="https://data.worldbank.org/" target="_blank" rel="noopener noreferrer">latest available World Bank figures</a> · New-market USD rates: <a href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html" target="_blank" rel="noopener noreferrer">ECB cross-rates, Sep 22 2026</a>, and <a href="https://www.cbr.ru/eng/currency_base/daily/?UniDbQuery.Posted=True&UniDbQuery.To=23.09.2026" target="_blank" rel="noopener noreferrer">Bank of Russia</a> for RUB; recheck before settlement · Tax treatment depends on entity, product, channel and destination</p><CapitalMarketRates code={market[1] as string} locale="en" /><MarketIntelligence code={market[1] as string} locale="en" /></div></div><p className="node-note"><CircleDot size={15}/> Hong Kong, China is Jiajia Health’s first overseas subsidiary and global investment launch point; Singapore remains the Southeast Asia resource node.</p></section>
    <CriticalPathAlerts locale="en" />
    <ExecutionWorkbench locale="en" />
    <PharmacyLaunchGuide locale="en" />
    <section className="roadmap-section" id="roadmap"><div className="section-topline dark"><div><div className="section-kicker light">18-MONTH ROADMAP</div><h2>A decision gate<br/>for every stage.</h2></div><p>Success is not measured by feature count, but by whether the platform operates, closes the loop and replicates.</p></div><div className="roadmap-grid">{stages.map((s,i)=><article key={s[0] as string}><div className="roadmap-head"><span>{s[0] as string}</span><b>{s[1] as string}</b></div><h3>{s[2] as string}</h3><ol>{(s[5] as string[]).map((x,j)=><li key={x}><span>0{j+1}</span>{x}</li>)}</ol><div className="roadmap-gate"><small>{s[3] as string}</small><strong>{s[4] as string}</strong><span className="roadmap-number">0{i+1}</span></div></article>)}</div></section>
    <section className="ai-section"><div className="ai-title"><div className="section-kicker">AI DELIVERY</div><h2>From productivity tools<br/>to platform capability.</h2><p>Buy tools first, agentise recurring workflows next, then turn high-frequency capabilities into durable products and owned data.</p></div><div className="ai-flow">{[[Search,'Research & compliance','Market rules and regulatory monitoring with professional confirmation.'],[Languages,'Content localisation','Turn one expert source into articles, FAQs, scripts and languages.'],[Database,'Products & supply','Structure labels, reports and certificates for global listings.'],[Bot,'User & buyer assistant','Answer, guide, match supply and generate RFQs from owned knowledge.']].map(([Icon,t,d],i)=>{const I=Icon as typeof Search;return <article key={t as string}><span className="ai-index">0{i+1}</span><I/><h3>{t as string}</h3><p>{d as string}</p></article>})}</div></section>
    <footer className="final-section"><div className="section-kicker light">TARGET STATE · MONTH 18</div><h2>From Hong Kong<br/>to a trusted global health network.</h2><p>Hong Kong connects investment and global resources; expertise earns trust, commerce serves demand, and AI plus data enable replication.</p><a className="primary-action" href="#markets">View market-entry strategy <ArrowUpRight/></a><div className="footer-meta"><span>JIAJIA HEALTH</span><span>GLOBAL HEALTH S2B2C</span><span>2026—2027</span></div></footer>
  </main>;
}
