export type Bi = { zh: string; en: string };
export type MarketFacts = { tax: string; population: string; gdp: string; fx: string; language: string; logistics: string };
type Intelligence = {
  trade: Bi; tradeSource: string; device: Bi; pharmacy: Bi; clinic: Bi; hospital: Bi;
  regulator: string; regulatorName: string; assessment: Bi; business: Bi;
};
export type EuropeanMarket = {
  code: string; name: Bi; role: Bi; model: Bi; detail: Bi; proof: { zh: string[]; en: string[] };
  facts: { zh: MarketFacts; en: MarketFacts }; coordinates: [number, number]; intelligence: Intelligence;
};
const b = (zh: string, en: string): Bi => ({ zh, en });
const euTrade = b('与中国的货物贸易适用欧盟共同贸易政策；药械准入、税务和药房经营仍须按目的国核查。', 'China trade follows the EU common trade policy; healthcare access, tax and pharmacy operation still require a destination-country review.');
const euTradeSource = 'https://policy.trade.ec.europa.eu/eu-trade-relationships-country-and-region/countries-and-regions/china_en';
const euDevice = b('按欧盟 MDR / IVDR 分类、合格评定及制造商／欧代／进口商责任核查。', 'Check EU MDR / IVDR classification, conformity and manufacturer / EU representative / importer duties.');

export const europeanMarkets: EuropeanMarket[] = [
  {
    code: 'FR', name: b('法国', 'France'), role: b('法语市场与欧盟医疗准入观察点', 'French-language EU health-market watchlist'), model: b('E2C + 持牌药房／器械伙伴', 'E2C + LICENSED PHARMACY / DEVICE PARTNERS'), coordinates: [2.3522, 48.8566],
    detail: b('先以法语内容和持牌合作测试需求；药品网售须由合资格实体药房经营，医疗机构另走地区卫生审批。', 'Test French-language content with licensed partners; medicine e-commerce belongs to eligible physical pharmacies, while care facilities follow regional health approvals.'),
    proof: { zh: ['法语内容', '持牌药房', '区域卫生审批'], en: ['French content', 'Licensed pharmacy', 'Regional health approval'] },
    facts: { zh: { tax: 'VAT 标准税率 20%；药品等可能适用低税率；跨境电商按目的地与 OSS 规则核税', population: '6,872 万', gdp: '3.37 万亿美元', fx: '1 USD ≈ 0.872 EUR', language: '法语', logistics: '巴黎／里昂仓配及欧盟陆运成熟；药品温控与跨境配送另核' }, en: { tax: 'Standard VAT 20%; eligible medicines may use reduced rates; assess destination and OSS rules for cross-border sales', population: '68.72m', gdp: 'US$3.37tn', fx: 'US$1 ≈ EUR0.872', language: 'French', logistics: 'Paris / Lyon and EU road network; medicine cold chain and cross-border delivery need separate review' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('网售须依附合资格实体药房；现行制度为事前申报，并核国家登记及欧盟共同标识。', 'Online medicine sales require an eligible physical pharmacy and prior declaration; verify national registration and the EU common logo.'), clinic: b('诊所按服务范围核地区卫生局及执业人员资格。', 'Check regional health authority and practitioner requirements by service.'), hospital: b('医院另核地区卫生局设施许可与规划。', 'Hospitals require separate regional facility authorisation and planning.'), regulator: 'https://www.ordre.pharmacien.fr/les-communications/focus-sur/les-actualites/vente-en-ligne-de-medicaments-a-usage-humain-demarches-prealables-actualisees-pour-le-pharmacien', regulatorName: '法国药师会 / CNOP', assessment: b('高：实体药房与网站绑定，设施许可另行。', 'High: website tied to a licensed pharmacy; facilities have a separate path.'), business: b('市场大但法语、数据保护、专业人员和地区审批需要本地团队。', 'Large market, but French language, privacy, professionals and regional approvals require local capacity.') },
  },
  {
    code: 'IT', name: b('意大利', 'Italy'), role: b('南欧医药制造与渠道观察点', 'Southern Europe pharma and channel watchlist'), model: b('B2B + 意语 E2C', 'B2B + ITALIAN E2C'), coordinates: [12.4964, 41.9028],
    detail: b('研究药企、批发和药房网络合作；药品网售仅限符合当地规定的非处方品类，医疗设施需看大区许可。', 'Study pharma, wholesale and pharmacy partnerships; online medicine sales are limited to eligible non-prescription products, and care facilities need regional review.'),
    proof: { zh: ['意语资料', '本地渠道', '大区许可'], en: ['Italian materials', 'Local channels', 'Regional permits'] },
    facts: { zh: { tax: 'VAT 标准税率 22%；药品及部分商品适用低税率；企业税和地区税另核', population: '5,892 万', gdp: '2.55 万亿美元', fx: '1 USD ≈ 0.872 EUR', language: '意大利语', logistics: '米兰／罗马节点与欧盟陆运、地中海港口相连；南北履约差异需测算' }, en: { tax: 'Standard VAT 22%; reduced rates may apply to medicines and selected goods; check corporate and regional taxes', population: '58.92m', gdp: 'US$2.55tn', fx: 'US$1 ≈ EUR0.872', language: 'Italian', logistics: 'Milan / Rome, EU roads and Mediterranean ports; cost northern and southern delivery separately' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('网售仅限获准药房／零售主体销售合资格非处方药；核当地登记与共同标识。', 'Only authorised pharmacies / retailers may sell eligible non-prescription medicines online; check registration and common logo.'), clinic: b('诊所按所在大区的设施和医师规则核查。', 'Clinics follow regional facility and practitioner rules.'), hospital: b('医院另涉大区设施批准与公共支付准入。', 'Hospitals add regional facility approval and reimbursement review.'), regulator: 'https://www.aifa.gov.it/en/-/vendita-di-farmaci-on-line-cosa-accade-in-italia', regulatorName: '意大利 AIFA / 卫生部', assessment: b('高：药品网售品类有限，大区医疗设施规则分层。', 'High: narrow online medicine scope and layered regional facility rules.'), business: b('医药制造基础深；意语、本地关系和大区差异是执行成本。', 'Strong pharma base; Italian-language operations, relationships and regional differences add cost.') },
  },
  {
    code: 'ES', name: b('西班牙', 'Spain'), role: b('西语内容与南欧渠道观察点', 'Spanish-language Southern Europe watchlist'), model: b('E2C + 持牌渠道合作', 'E2C + LICENSED CHANNELS'), coordinates: [-3.7038, 40.4168],
    detail: b('可验证西语内容，但网上药品销售仅能由获准实体药房直接经营，不能把平台做成药品交易中介。', 'Spanish content is reusable, but online medicine sales must be direct from authorised physical pharmacies rather than a marketplace intermediary.'),
    proof: { zh: ['西语内容', '药房直售规则', '自治地区许可'], en: ['Spanish content', 'Pharmacy-direct rules', 'Regional licences'] },
    facts: { zh: { tax: 'VAT 标准税率 21%；部分医药品类适用低税率；跨境网售按目的地规则核税', population: '4,936 万', gdp: '1.91 万亿美元', fx: '1 USD ≈ 0.872 EUR', language: '西班牙语 · 地区语言', logistics: '马德里／巴塞罗那仓配与伊比利亚陆运；岛屿配送另估成本' }, en: { tax: 'Standard VAT 21%; some health products qualify for reduced rates; apply destination VAT rules to cross-border sales', population: '49.36m', gdp: 'US$1.91tn', fx: 'US$1 ≈ EUR0.872', language: 'Spanish · regional languages', logistics: 'Madrid / Barcelona and Iberian roads; cost island delivery separately' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('AEMPS 明确非处方药网售仅由登记的实体药房直接完成，不得以第三方平台中介下单。', 'AEMPS limits online non-prescription medicine sales to registered physical pharmacies selling directly, without marketplace intermediation.'), clinic: b('诊所按自治地区卫生许可与专业人员登记核查。', 'Clinics need autonomous-community health authorisation and professional registration.'), hospital: b('医院设施与床位／服务项目按自治地区分别审批。', 'Hospitals require autonomous-community approval for facilities and services.'), regulator: 'https://www.aemps.gob.es/informa/medIlegales/informacion-sobre-la-venta-de-medicamentos-a-traves-de-sitios-web-y-aplicaciones-para-moviles/', regulatorName: '西班牙 AEMPS', assessment: b('高：药品平台中介受限，自治地区另审医疗设施。', 'High: pharmacy-direct rule restricts marketplaces; regions govern care facilities.'), business: b('可复用西语内容能力；但不能复制墨西哥的药品交易流程。', 'Spanish content can be reused, but Mexico’s medicine-commerce flow cannot be copied.') },
  },
  {
    code: 'NL', name: b('荷兰', 'Netherlands'), role: b('欧洲物流与生命科学连接点', 'European logistics and life-science node'), model: b('B2B + E2C 机构合作', 'B2B + E2C PARTNERSHIPS'), coordinates: [4.9041, 52.3676],
    detail: b('优先评估进口分销、器械合作与专家网络；药品网站面向荷兰消费者时适用当地药品与广告规则。', 'Prioritise import, device and expert partnerships; websites targeting Dutch consumers are subject to Dutch medicine and advertising rules.'),
    proof: { zh: ['鹿特丹物流', '持牌分销', '荷兰语合规'], en: ['Rotterdam logistics', 'Licensed distribution', 'Dutch compliance'] },
    facts: { zh: { tax: 'VAT 标准税率 21%；药品等可能适用 9%；企业所得税与跨境税务另核', population: '1,809 万', gdp: '1.33 万亿美元', fx: '1 USD ≈ 0.872 EUR', language: '荷兰语 · 英语广泛使用', logistics: '鹿特丹港／史基浦机场连接欧盟；跨境药品配送按目的地限制' }, en: { tax: 'Standard VAT 21%; eligible medicines may use 9%; check corporate and cross-border taxes separately', population: '18.09m', gdp: 'US$1.33tn', fx: 'US$1 ≈ EUR0.872', language: 'Dutch · English widely used', logistics: 'Rotterdam / Schiphol connect the EU; medicine delivery depends on destination rules' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('网站面向荷兰消费者须满足药品法、药师及广告规则；核国家网上零售登记。', 'A website targeting Dutch consumers must meet Dutch medicines, pharmacist and advertising rules; check the national online-retailer register.'), clinic: b('医疗服务主体另核 Wtza 通知／许可及执业登记。', 'Care providers separately assess Wtza notification / permit and professional registration.'), hospital: b('医院及私营诊疗设施另核 Wtza 与质量监督。', 'Hospitals and private care facilities need Wtza and quality-supervision review.'), regulator: 'https://www.igj.nl/onderwerpen/medicijnen/online-medicijnen/toezicht-op-online-medicijnen', regulatorName: '荷兰 IGJ', assessment: b('中高：物流强，但药品网售和医疗服务分属许可线。', 'Medium–high: strong logistics but medicine and care licences are separate.'), business: b('欧洲分销效率高；荷语面向消费者的药品规则和本地责任主体不可省。', 'Efficient EU distribution; Dutch consumer-medicine rules and local accountability matter.') },
  },
  {
    code: 'CH', name: b('瑞士', 'Switzerland'), role: b('非欧盟生命科学与高端器械市场', 'Non-EU life-science and premium-device market'), model: b('B2B + 高标准机构合作', 'B2B + SPECIALIST PARTNERSHIPS'), coordinates: [8.5417, 47.3769],
    detail: b('瑞士不是欧盟成员；须独立核 Swissmedic 药械路径、进口责任和州级药房／医疗机构许可。', 'Switzerland is outside the EU; Swissmedic product access, import responsibility and cantonal pharmacy / care licences need separate assessment.'),
    proof: { zh: ['Swissmedic 路径', '州级许可', '高端渠道'], en: ['Swissmedic pathway', 'Cantonal licences', 'Specialist channels'] },
    facts: { zh: { tax: 'VAT 标准税率 8.1%；药品可能适用低税率；企业税随联邦、州和市镇变化', population: '909 万', gdp: '1.04 万亿美元', fx: '1 USD ≈ 0.821 CHF', language: '德语 · 法语 · 意大利语', logistics: '苏黎世／巴塞尔接欧盟陆运；非欧盟清关与温控需单独设计' }, en: { tax: 'Standard VAT 8.1%; medicines may qualify for reduced rates; corporate taxes vary by federal, canton and municipality level', population: '9.09m', gdp: 'US$1.04tn', fx: 'US$1 ≈ CHF0.821', language: 'German · French · Italian', logistics: 'Zurich / Basel links to EU roads; non-EU customs and cold chain need separate design' } },
    intelligence: { trade: b('瑞中自贸协定已生效，但不替代瑞士药械注册、进口许可或州级医疗经营许可。', 'The Switzerland–China FTA is in force, but does not replace Swiss product, import or cantonal healthcare licences.'), tradeSource: 'https://www.seco.admin.ch/en/free-trade-agreement-china', device: b('瑞士医疗器械规则和本地代表／进口义务须与欧盟路径分开核查。', 'Check Swiss device rules and local representative / importer duties separately from EU access.'), pharmacy: b('药品邮购原则上受限；须持相关州级邮购许可，每笔订单按规定提交处方。', 'Medicine mail order is restricted; a cantonal mail-order licence and prescription for each order are required.'), clinic: b('诊所按所在地州法、医师资格与设施规则核查。', 'Clinics follow canton-specific facility and practitioner rules.'), hospital: b('医院另涉州级运营许可、规划与保险支付准入。', 'Hospitals add canton-level operating approval, planning and insurance access.'), regulator: 'https://www.swissmedic.ch/swissmedic/en/home/humanarzneimittel/market-surveillance/medicinal-products-from-the-internet/leitfaden-arzneimittel-aus-dem-internet.html', regulatorName: '瑞士 Swissmedic', assessment: b('高：非欧盟准入独立，州级药房和医疗许可并行。', 'High: separate non-EU pathway and cantonal pharmacy / care licences.'), business: b('生命科学集群和购买力强；多语、较高经营成本与瑞士独立清关需预算。', 'Strong life sciences and purchasing power; budget for multilingual work, higher costs and separate customs.') },
  },
  {
    code: 'PL', name: b('波兰', 'Poland'), role: b('中东欧人口与配送观察点', 'Central European population and delivery watchlist'), model: b('B2B + 波兰语 E2C', 'B2B + POLISH E2C'), coordinates: [21.0122, 52.2297],
    detail: b('把波兰作为中东欧仓配和渠道研究点；药店网上销售以获准实体药房的非处方药规则为前提。', 'Study Poland as a Central European distribution node; online medicine sales follow licensed-pharmacy and non-prescription rules.'),
    proof: { zh: ['波兰语内容', '药房许可', '中东欧仓配'], en: ['Polish content', 'Pharmacy licence', 'CEE fulfilment'] },
    facts: { zh: { tax: 'VAT 标准税率 23%；医药品类及跨境网售按目的地、商品和 OSS 规则核税', population: '3,644 万', gdp: '1.04 万亿美元', fx: '1 USD ≈ 3.79 PLN', language: '波兰语', logistics: '华沙与中东欧公路网络；欧盟境内分销便利但温控药品须单独核查' }, en: { tax: 'Standard VAT 23%; healthcare and cross-border sales require product, destination and OSS assessment', population: '36.44m', gdp: 'US$1.04tn', fx: 'US$1 ≈ PLN3.79', language: 'Polish', logistics: 'Warsaw and Central European road network; regulated cold-chain medicines need separate review' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('持牌实体药房可按条件远程销售非处方药；开售前核省级药监通知与网站要求。', 'A licensed physical pharmacy may sell eligible OTC medicines remotely; check provincial inspection notification and website rules.'), clinic: b('诊所主体与医师按 RPWDL 等登记路径核查。', 'Clinics and professionals need RPWDL and related registration review.'), hospital: b('医院另需医疗活动主体登记、设施及支付安排核验。', 'Hospitals require separate provider registration, premises and payment review.'), regulator: 'https://www.gov.pl/web/zdrowie/apteki-ogolnodostepne', regulatorName: '波兰卫生部 / GIF', assessment: b('中高：有中东欧物流优势，药房与医疗登记仍有前置门槛。', 'Medium–high: good CEE logistics, but pharmacy and care registrations remain gates.'), business: b('成本相对西欧可控；波兰语、当地税务和牌照仍须本地化。', 'Costs can be lower than Western Europe; Polish language, tax and licences remain local workstreams.') },
  },
  {
    code: 'IE', name: b('爱尔兰', 'Ireland'), role: b('英语生命科学与欧盟运营观察点', 'English-language EU life-science watchlist'), model: b('E2C + 医药产业合作', 'E2C + LIFE-SCIENCE PARTNERSHIPS'), coordinates: [-6.2603, 53.3498],
    detail: b('利用英语与生命科学产业集群研究合作；处方药不能网上销售，非处方药供应主体须进入监管名录。', 'Explore English-language and life-science partnerships; prescription medicines cannot be sold online and OTC suppliers must appear on the regulator list.'),
    proof: { zh: ['英语内容', '生命科学伙伴', 'PSI 线上名单'], en: ['English content', 'Life-science partners', 'PSI online register'] },
    facts: { zh: { tax: 'VAT 标准税率 23%；企业税和医药品类依主体、活动与适用规则核算', population: '548 万', gdp: '7,217 亿美元', fx: '1 USD ≈ 0.872 EUR', language: '英语 · 爱尔兰语', logistics: '都柏林航空与港口连接欧盟／英国；岛屿海运和医药冷链需测算' }, en: { tax: 'Standard VAT 23%; corporate and healthcare-product treatment depends on entity and activity', population: '5.48m', gdp: 'US$721.7bn', fx: 'US$1 ≈ EUR0.872', language: 'English · Irish', logistics: 'Dublin air and sea links to EU / UK; price island shipping and pharma cold chain' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('HPRA 明确处方药不得网上供应；非处方药网上卖家须进入 PSI Internet Supply List。', 'HPRA states prescription medicines cannot be supplied online; OTC sellers need entry on the PSI Internet Supply List.'), clinic: b('诊所与专业人员登记按具体服务核查。', 'Check care-service and professional registration by activity.'), hospital: b('医院另核服务、设施与人员监管；不以公司注册替代医疗许可。', 'Hospitals need separate service, facility and staffing review; incorporation is not a care licence.'), regulator: 'https://www.hpra.ie/safety-information/how-we-monitor-safety/medicines/dangers-of-buying-prescription-medicines-online', regulatorName: '爱尔兰 HPRA / PSI', assessment: b('高：医药网售边界明确，机构经营仍须独立核查。', 'High: online medicine boundary is clear; care provision needs separate review.'), business: b('英语及医药产业优势明显；名义 GDP 受跨国企业活动影响，不宜直接当本地需求。', 'English and life-science strengths; multinational activity distorts nominal GDP as a proxy for local demand.') },
  },
  {
    code: 'SE', name: b('瑞典', 'Sweden'), role: b('北欧数字健康与药房观察点', 'Nordic digital-health and pharmacy watchlist'), model: b('E2C + 持牌药房合作', 'E2C + LICENSED PHARMACY PARTNERS'), coordinates: [18.0686, 59.3293],
    detail: b('研究数字健康、专家内容与药房伙伴；线上药品经营须有药房许可，并提前向药监机构申报远程／电商业务。', 'Study digital health, expert content and pharmacy partners; online medicine supply needs a pharmacy licence and advance notification of distance / e-commerce activity.'),
    proof: { zh: ['瑞典语内容', '药房许可', '提前申报'], en: ['Swedish content', 'Pharmacy licence', 'Advance notification'] },
    facts: { zh: { tax: 'VAT 标准税率 25%；药品及医疗服务适用规则与一般电商不同', population: '1,060 万', gdp: '6,690 亿美元', fx: '1 USD ≈ 9.81 SEK', language: '瑞典语 · 英语广泛使用', logistics: '斯德哥尔摩／哥德堡及北欧包裹网络；人口分散地区配送成本需估算' }, en: { tax: 'Standard VAT 25%; medicine and healthcare-service treatment differs from ordinary commerce', population: '10.60m', gdp: 'US$669.0bn', fx: 'US$1 ≈ SEK9.81', language: 'Swedish · English widely used', logistics: 'Stockholm / Gothenburg and Nordic parcels; price sparse-area delivery' } },
    intelligence: { trade: euTrade, tradeSource: euTradeSource, device: euDevice, pharmacy: b('药房经营须获许可；药品远程／电商活动须提前至少两个月向药监机构申报。', 'A pharmacy licence is required; distance / e-commerce medicine activity must be notified to the medicines agency at least two months in advance.'), clinic: b('医疗服务提供者须按 IVO 规则提前登记，部分业务另需许可。', 'Care providers must register with IVO in advance; some activities require a permit.'), hospital: b('医院另核 IVO、地区医疗服务安排及人员条件。', 'Hospitals need IVO, regional service and staffing review.'), regulator: 'https://www.lakemedelsverket.se/sv/handel-med-lakemedel/apotek/distans--och-e-handel-pa-apotek', regulatorName: '瑞典药监局 / Läkemedelsverket', assessment: b('中高：规则透明，但药房许可与提前申报会影响排期。', 'Medium–high: transparent rules, but pharmacy licensing and advance notice affect timing.'), business: b('数字化和英语环境较好；瑞典语消费者沟通、用工与地域配送成本要计入。', 'Digital readiness and English help; budget for Swedish consumer content, labour and dispersed delivery.') },
  },
];

export const europeanIntelligence: Record<string, Intelligence> = Object.fromEntries(europeanMarkets.map((market) => [market.code, market.intelligence]));
