// Complete indicator directory adapted from the user-provided reference.
export type FullCatalogGroup = { id: string; zh: string; en: string; indicators: string[] };
export const fullCatalog: FullCatalogGroup[] = [
  {
    "id": "01",
    "zh": "总体经济规模与增长",
    "en": "National Accounts",
    "indicators": [
      "名义 GDP（Nominal GDP）",
      "实际 GDP（Real GDP）",
      "实际 GDP 同比增速",
      "实际 GDP 环比增速",
      "季调年化 GDP 增速",
      "人均 GDP",
      "实际人均 GDP",
      "PPP 人均 GDP",
      "GNI 国民总收入",
      "人均 GNI",
      "NNI 国民净收入",
      "GDP 平减指数",
      "潜在 GDP（Potential GDP）",
      "产出缺口（Output Gap）",
      "国内最终需求",
      "私人消费",
      "政府消费",
      "固定资本形成",
      "Gross Fixed Capital Formation",
      "住宅投资",
      "企业固定投资",
      "基础设施投资",
      "库存变化",
      "净出口",
      "国民储蓄率",
      "国内投资率",
      "储蓄－投资缺口",
      "GDP 中农业占比",
      "工业占比",
      "制造业占比",
      "建筑业占比",
      "服务业占比"
    ]
  },
  {
    "id": "02",
    "zh": "经济活动高频指标",
    "en": "High-Frequency Activity",
    "indicators": [
      "工业增加值 / Industrial Production",
      "制造业产出",
      "服务业产出",
      "零售销售",
      "批发销售",
      "汽车销量",
      "电力消费",
      "货运量",
      "港口吞吐量",
      "航空客运量",
      "铁路货运",
      "快递量",
      "新订单",
      "耐用品订单",
      "企业库存",
      "库存销售比",
      "产能利用率",
      "Manufacturing PMI",
      "Services PMI",
      "Composite PMI",
      "商业信心指数",
      "消费者信心指数",
      "领先经济指标 LEI",
      "同步经济指标",
      "经济意外指数 Economic Surprise Index"
    ]
  },
  {
    "id": "03",
    "zh": "通胀与价格",
    "en": "Inflation & Prices",
    "indicators": [
      "CPI",
      "CPI 同比",
      "CPI 环比",
      "Core CPI",
      "核心服务通胀",
      "商品通胀",
      "食品通胀",
      "能源通胀",
      "住房/租金通胀",
      "PPI 生产者价格指数",
      "核心 PPI",
      "GDP Deflator",
      "PCE Inflation（适用于美国等）",
      "Core PCE",
      "进口价格指数",
      "出口价格指数",
      "批发价格指数",
      "建筑成本指数",
      "房价通胀",
      "工资通胀",
      "单位劳动成本 Unit Labor Cost",
      "通胀预期 1Y",
      "通胀预期 5Y",
      "通胀预期 10Y",
      "市场 Breakeven Inflation"
    ]
  },
  {
    "id": "04",
    "zh": "就业与劳动力市场",
    "en": "Labor Market",
    "indicators": [
      "失业率",
      "青年失业率",
      "长期失业率",
      "就业人数",
      "就业增长",
      "就业率",
      "劳动参与率",
      "劳动年龄人口",
      "劳动力总量",
      "非农就业（适用国家）",
      "私营部门就业",
      "公共部门就业",
      "全职就业",
      "兼职就业",
      "不充分就业率 Underemployment",
      "U6 类广义失业率",
      "职位空缺数",
      "Vacancy Rate",
      "招聘率",
      "离职率 / Quit Rate",
      "裁员率",
      "平均工作时长",
      "平均时薪",
      "平均月薪",
      "中位数工资",
      "名义工资增速",
      "实际工资增速",
      "劳动生产率",
      "单位劳动成本",
      "NEET 比例",
      "非正规就业比例",
      "外籍劳动力占比"
    ]
  },
  {
    "id": "05",
    "zh": "居民收入与消费",
    "en": "Households",
    "indicators": [
      "居民可支配收入",
      "实际可支配收入",
      "人均可支配收入",
      "家庭消费支出",
      "消费占 GDP",
      "家庭储蓄率",
      "家庭净财富",
      "家庭金融资产",
      "家庭房地产资产",
      "家庭总债务",
      "Household Debt / GDP",
      "家庭债务 / 可支配收入",
      "Household Debt Service Ratio",
      "信用卡债务",
      "按揭贷款",
      "消费贷款",
      "贷款拖欠率",
      "房贷拖欠率",
      "消费者信心",
      "实际零售消费"
    ]
  },
  {
    "id": "06",
    "zh": "收入分配与生活水平",
    "en": "Income & Living Standards",
    "indicators": [
      "人均收入",
      "中位数家庭收入",
      "实际中位数收入",
      "Gini 系数",
      "最富 10% 收入占比",
      "最富 1% 收入占比",
      "最低 50% 收入占比",
      "相对贫困率",
      "绝对贫困率",
      "生活成本指数",
      "实际购买力",
      "PPP 消费水平",
      "住房成本 / 收入",
      "租金负担率",
      "能源负担率"
    ]
  },
  {
    "id": "07",
    "zh": "政府财政",
    "en": "Fiscal",
    "indicators": [
      "政府总收入",
      "政府总支出",
      "财政收入 / GDP",
      "财政支出 / GDP",
      "财政余额",
      "财政赤字 / GDP",
      "Primary Balance 基本财政余额",
      "Primary Balance / GDP",
      "结构性财政余额",
      "周期调整财政余额",
      "税收收入 / GDP",
      "个人所得税收入",
      "企业所得税收入",
      "VAT / GST 收入",
      "社保缴费收入",
      "政府投资",
      "社会福利支出",
      "医疗支出",
      "养老金支出",
      "国防支出",
      "教育支出",
      "财政冲动 Fiscal Impulse",
      "政府现金余额"
    ]
  },
  {
    "id": "08",
    "zh": "政府债务",
    "en": "Sovereign Debt",
    "indicators": [
      "General Government Gross Debt",
      "Government Net Debt",
      "Debt / GDP",
      "中央政府债务",
      "地方政府债务",
      "公共部门债务",
      "国企债务",
      "政府担保债务",
      "或有负债",
      "PPP 隐性负债",
      "养老金隐性负债",
      "政府债务平均期限",
      "债务久期",
      "年内到期债务",
      "未来 1 年再融资需求",
      "未来 3 年再融资需求",
      "Gross Financing Need",
      "债务利息支出",
      "利息支出 / GDP",
      "利息支出 / 财政收入",
      "平均融资成本",
      "固定利率债务占比",
      "浮动利率债务占比",
      "本币债务占比",
      "外币政府债务占比",
      "国内投资者持债占比",
      "外国投资者持债占比",
      "银行持政府债占比",
      "央行持政府债占比"
    ]
  },
  {
    "id": "09",
    "zh": "利率与货币政策",
    "en": "Monetary Policy",
    "indicators": [
      "央行政策利率",
      "隔夜利率",
      "银行间拆借利率",
      "回购利率 Repo Rate",
      "逆回购利率",
      "常备借贷便利利率",
      "存款便利利率",
      "贷款便利利率",
      "法定存款准备金率",
      "央行公开市场操作量",
      "实际政策利率",
      "Taylor-rule implied rate（分析指标）",
      "金融条件指数 Financial Conditions Index"
    ]
  },
  {
    "id": "10",
    "zh": "国债收益率曲线",
    "en": "Yield Curve",
    "indicators": [
      "3M 国债",
      "6M",
      "1Y",
      "2Y",
      "3Y",
      "5Y",
      "7Y",
      "10Y",
      "15Y",
      "20Y",
      "30Y",
      "50Y（如有）",
      "2Y–10Y Spread",
      "3M–10Y Spread",
      "1Y–10Y Spread",
      "实际国债收益率",
      "通胀保值债收益率",
      "Sovereign CDS",
      "相对基准国债利差"
    ]
  },
  {
    "id": "11",
    "zh": "货币供应与央行资产负债表",
    "en": "Money & Central Bank",
    "indicators": [
      "Monetary Base",
      "M0",
      "M1",
      "M2",
      "M3",
      "货币供应增速",
      "货币乘数",
      "银行准备金",
      "超额准备金",
      "央行资产规模",
      "央行资产 / GDP",
      "政府债持仓",
      "外汇资产",
      "黄金储备",
      "QE 规模",
      "QT 规模",
      "央行对银行贷款"
    ]
  },
  {
    "id": "12",
    "zh": "银行体系",
    "en": "Banking",
    "indicators": [
      "银行总资产",
      "银行信贷 / GDP",
      "银行贷款增速",
      "企业贷款",
      "房贷",
      "消费贷",
      "存款总额",
      "存款增长",
      "Loan-to-Deposit Ratio",
      "NPL 不良贷款率",
      "Stage 2 / Stage 3 Loans",
      "拨备覆盖率",
      "CET1",
      "Tier 1 Capital Ratio",
      "总资本充足率",
      "Liquidity Coverage Ratio",
      "Net Stable Funding Ratio",
      "银行 ROA",
      "银行 ROE",
      "净息差 NIM",
      "银行融资成本",
      "存贷利差",
      "银行外币负债",
      "银行外汇敞口",
      "银行对房地产敞口",
      "银行对政府敞口"
    ]
  },
  {
    "id": "13",
    "zh": "信用与杠杆",
    "en": "Credit & Leverage",
    "indicators": [
      "Private Credit / GDP",
      "信贷增速",
      "Credit-to-GDP Gap",
      "企业债务 / GDP",
      "家庭债务 / GDP",
      "政府债务 / GDP",
      "Total Economy Debt / GDP",
      "金融部门债务",
      "非金融企业债务",
      "杠杆率",
      "Debt Service Ratio",
      "Interest Coverage Ratio",
      "企业违约率",
      "债券违约额",
      "破产企业数量"
    ]
  },
  {
    "id": "14",
    "zh": "资本市场",
    "en": "Capital Markets",
    "indicators": [
      "股票市场总市值",
      "Market Cap / GDP",
      "主要股指",
      "股市年涨跌幅",
      "P/E",
      "Forward P/E",
      "CAPE",
      "P/B",
      "Dividend Yield",
      "Equity Risk Premium",
      "企业债收益率",
      "Investment Grade Spread",
      "High Yield Spread",
      "企业债市场规模",
      "政府债市场规模",
      "新股融资 IPO",
      "企业债发行量",
      "股票成交额",
      "债券成交额",
      "市场波动率"
    ]
  },
  {
    "id": "15",
    "zh": "房地产",
    "en": "Real Estate",
    "indicators": [
      "Residential House Price Index",
      "实际房价",
      "房价同比",
      "房价 / 收入",
      "房价 / 租金",
      "Rental Yield",
      "租金指数",
      "空置率",
      "新屋开工",
      "Building Permits",
      "新房销售",
      "二手房销售",
      "房屋库存",
      "库存销售比",
      "房贷利率",
      "Mortgage Debt",
      "平均 LTV",
      "平均 DTI",
      "按揭违约率",
      "房地产投资 / GDP",
      "建筑业 / GDP",
      "Commercial Real Estate Price Index",
      "办公室空置率",
      "商业地产资本化率",
      "开发商债务"
    ]
  },
  {
    "id": "16",
    "zh": "国际贸易",
    "en": "International Trade",
    "indicators": [
      "商品出口",
      "商品进口",
      "商品贸易余额",
      "服务出口",
      "服务进口",
      "服务贸易余额",
      "总出口 / GDP",
      "总进口 / GDP",
      "Trade Openness",
      "制造业出口",
      "高技术产品出口",
      "能源出口",
      "能源进口",
      "农产品出口",
      "主要出口目的国",
      "主要进口来源国",
      "出口集中度",
      "产品集中度",
      "Terms of Trade",
      "出口价格",
      "进口价格"
    ]
  },
  {
    "id": "17",
    "zh": "国际收支",
    "en": "Balance of Payments",
    "indicators": [
      "Current Account",
      "Current Account / GDP",
      "Goods Balance",
      "Services Balance",
      "Primary Income Balance",
      "Secondary Income Balance",
      "Capital Account",
      "Financial Account",
      "FDI Inflows",
      "FDI Outflows",
      "Portfolio Inflows",
      "Portfolio Outflows",
      "Other Investment Flows",
      "Errors and Omissions",
      "Reserve Asset Change"
    ]
  },
  {
    "id": "18",
    "zh": "国际投资头寸",
    "en": "International Investment Position",
    "indicators": [
      "NIIP Net International Investment Position",
      "NIIP / GDP",
      "对外总资产",
      "对外总负债",
      "FDI 资产",
      "FDI 负债",
      "证券投资资产",
      "证券投资负债",
      "银行跨境资产",
      "银行跨境负债"
    ]
  },
  {
    "id": "19",
    "zh": "外债",
    "en": "External Debt",
    "indicators": [
      "Gross External Debt",
      "External Debt / GDP",
      "Net External Debt",
      "政府外债",
      "银行外债",
      "企业外债",
      "短期外债",
      "长期外债",
      "Short-term External Debt / Reserves",
      "外债偿付额",
      "External Debt Service / Exports",
      "外国人持有本国债务",
      "外债平均期限"
    ]
  },
  {
    "id": "20",
    "zh": "外币债务",
    "en": "Currency Mismatch",
    "indicators": [
      "外币债务总额",
      "Foreign Currency Debt / GDP",
      "美元债务",
      "欧元债务",
      "日元债务",
      "企业外币债",
      "政府外币债",
      "银行外币负债",
      "未对冲外汇敞口",
      "FX mismatch",
      "外币收入 / 外币债务"
    ]
  },
  {
    "id": "21",
    "zh": "外汇储备",
    "en": "International Reserves",
    "indicators": [
      "Gross FX Reserves",
      "黄金储备",
      "SDR",
      "IMF Reserve Position",
      "Net International Reserves",
      "可用储备",
      "Reserves / GDP",
      "Reserves / Imports",
      "Months of Import Cover",
      "Reserves / Short-term External Debt",
      "Guidotti-Greenspan Ratio",
      "IMF ARA reserve adequacy ratio",
      "储备变化速度",
      "央行远期外汇头寸",
      "外汇掉期头寸"
    ]
  },
  {
    "id": "22",
    "zh": "汇率",
    "en": "Foreign Exchange",
    "indicators": [
      "USD/本币",
      "EUR/本币",
      "JPY/本币等主要交叉汇率",
      "NEER",
      "REER",
      "实际汇率高估/低估估计",
      "汇率年波动率",
      "汇率制度",
      "货币篮子构成",
      "Currency Forward Rate",
      "FX Swap Basis",
      "Offshore/Onshore Spread",
      "黑市汇率（部分国家）",
      "央行外汇干预量"
    ]
  },
  {
    "id": "23",
    "zh": "跨境资本流动",
    "en": "Cross-Border Capital Flows",
    "indicators": [
      "Foreign Portfolio Flow",
      "Equity Flow",
      "Bond Flow",
      "FDI Flow",
      "Banking Flow",
      "Carry Trade Exposure",
      "非居民持债占比",
      "非居民持股占比",
      "国内资本外流",
      "Capital Flight proxy",
      "资本管制程度"
    ]
  },
  {
    "id": "24",
    "zh": "企业部门",
    "en": "Corporate Sector",
    "indicators": [
      "企业利润",
      "Corporate Profits / GDP",
      "营业利润率",
      "EBITDA Margin",
      "企业投资",
      "企业现金流",
      "企业债务",
      "Corporate Debt / GDP",
      "企业债收益率",
      "Interest Coverage Ratio",
      "Debt/EBITDA",
      "企业违约率",
      "企业破产率",
      "企业库存",
      "企业信心",
      "新企业注册数量",
      "企业注销数量"
    ]
  },
  {
    "id": "25",
    "zh": "生产率与长期增长",
    "en": "Productivity & Long-Term Growth",
    "indicators": [
      "Labor Productivity",
      "Output per Hour",
      "Output per Worker",
      "TFP 全要素生产率",
      "Capital Productivity",
      "单位劳动成本",
      "潜在 GDP 增长率",
      "潜在劳动供给",
      "潜在资本增长",
      "潜在生产率增长"
    ]
  },
  {
    "id": "26",
    "zh": "人口",
    "en": "Demographics",
    "indicators": [
      "总人口",
      "人口增长率",
      "出生率",
      "死亡率",
      "总和生育率",
      "预期寿命",
      "中位年龄",
      "0–14 岁占比",
      "15–64 岁占比",
      "65+ 占比",
      "Working-age Population",
      "老年抚养比",
      "总抚养比",
      "净移民",
      "移民人口占比",
      "城镇化率",
      "家庭规模"
    ]
  },
  {
    "id": "27",
    "zh": "教育与人力资本",
    "en": "Education & Human Capital",
    "indicators": [
      "平均受教育年限",
      "高等教育入学率",
      "大学毕业率",
      "STEM 毕业生",
      "PISA 等教育测试",
      "Human Capital Index",
      "技能水平",
      "职业教育参与率",
      "教育支出 / GDP",
      "教育支出 / 财政支出"
    ]
  },
  {
    "id": "28",
    "zh": "创新与技术",
    "en": "Innovation & Technology",
    "indicators": [
      "R&D / GDP",
      "企业 R&D",
      "政府 R&D",
      "专利申请",
      "国际专利",
      "科研论文",
      "高技术产品出口",
      "ICT 投资",
      "软件投资",
      "AI 投资",
      "风险投资",
      "创业融资",
      "独角兽数量",
      "技术密集型就业占比",
      "机器人密度",
      "半导体产能等国家特定指标"
    ]
  },
  {
    "id": "29",
    "zh": "能源与资源",
    "en": "Energy & Resources",
    "indicators": [
      "总能源消费",
      "人均能源消费",
      "电力消费",
      "发电量",
      "能源进口依赖度",
      "石油进口",
      "石油出口",
      "天然气进口",
      "煤炭消费",
      "电价",
      "工业电价",
      "可再生能源占比",
      "核电占比",
      "能源强度",
      "战略石油储备",
      "矿产出口依赖"
    ]
  },
  {
    "id": "30",
    "zh": "产业结构",
    "en": "Industrial Structure",
    "indicators": [
      "农业增加值",
      "制造业增加值",
      "高端制造业占比",
      "建筑业增加值",
      "金融业增加值",
      "科技行业增加值",
      "医疗行业增加值",
      "房地产业增加值",
      "旅游业占 GDP",
      "出口制造业占比",
      "中小企业占比",
      "国企占经济比例",
      "私营经济占比"
    ]
  },
  {
    "id": "31",
    "zh": "国际竞争力",
    "en": "International Competitiveness",
    "indicators": [
      "Unit Labor Cost",
      "REER",
      "劳动生产率",
      "制造业工资",
      "企业税率",
      "电力成本",
      "土地成本",
      "物流成本",
      "港口效率",
      "基础设施质量",
      "Broadband penetration",
      "Digitalization",
      "R&D",
      "专利",
      "出口市场份额",
      "世界出口份额",
      "世界制造业份额"
    ]
  },
  {
    "id": "32",
    "zh": "主权信用与市场风险",
    "en": "Sovereign Credit & Market Risk",
    "indicators": [
      "S&P sovereign rating",
      "Moody's rating",
      "Fitch rating",
      "Sovereign CDS",
      "国债与美债/德债利差",
      "外币债 spread",
      "本币债 spread",
      "Auction Bid-to-Cover",
      "国债拍卖尾差",
      "外国投资者持债变化",
      "政府融资需求",
      "Debt Rollover Risk"
    ]
  },
  {
    "id": "33",
    "zh": "社会保障与长期财政",
    "en": "Social Security & Long-Term Fiscal",
    "indicators": [
      "养老金支出 / GDP",
      "医疗支出 / GDP",
      "长期护理支出",
      "养老金替代率",
      "养老金基金资产",
      "Unfunded Pension Liability",
      "社保缴费率",
      "退休年龄",
      "老龄化相关未来财政缺口"
    ]
  },
  {
    "id": "34",
    "zh": "贫富与社会经济稳定",
    "en": "Inequality & Social Stability",
    "indicators": [
      "Gini",
      "财富 Gini",
      "收入前 1%",
      "财富前 1%",
      "中等收入群体占比",
      "青年失业",
      "房价收入比",
      "实际工资",
      "食品价格负担",
      "能源价格负担"
    ]
  },
  {
    "id": "35",
    "zh": "国家经济制度变量",
    "en": "Economic Institutions",
    "indicators": [
      "汇率制度",
      "资本账户开放程度",
      "央行独立性",
      "通胀目标",
      "财政规则",
      "Debt Brake",
      "货币局制度",
      "是否美元化/欧元化",
      "养老金制度",
      "医疗融资制度",
      "最低工资制度",
      "劳动力市场制度",
      "税收制度",
      "贸易协定",
      "产业补贴制度"
    ]
  },
  {
    "id": "36",
    "zh": "环境与气候经济指标",
    "en": "Climate & Environment",
    "indicators": [
      "CO₂ / GDP",
      "人均 CO₂",
      "碳价",
      "能源强度",
      "可再生能源比例",
      "气候灾害经济损失",
      "保险损失",
      "绿色投资",
      "Green Bond issuance",
      "气候相关财政风险"
    ]
  }
];
