export type CatalogGroup = { id: string; zh: string; en: string; indicators: [string, string][] };

export const macroCatalog: CatalogGroup[] = [
  { id: 'growth', zh: '经济增长', en: 'Growth', indicators: [['名义 GDP','Nominal GDP'],['实际 GDP 增速','Real GDP growth'],['人均 GDP','GDP per capita'],['PPP 人均 GDP','PPP GDP per capita'],['国民总收入','GNI'],['消费与投资','Consumption and investment'],['国民储蓄率','National saving rate'],['产出缺口','Output gap'],['产业增加值结构','Sector value added']] },
  { id: 'inflation', zh: '通胀与价格', en: 'Inflation & Prices', indicators: [['CPI 同比与环比','CPI annual and monthly'],['核心 CPI','Core CPI'],['食品、能源和住房通胀','Food, energy and shelter inflation'],['PPI','Producer prices'],['GDP 平减指数','GDP deflator'],['工资与单位劳动成本','Wages and unit labor cost'],['房价指数','House price index'],['通胀预期','Inflation expectations']] },
  { id: 'labor', zh: '就业与劳动力', en: 'Labor', indicators: [['失业率','Unemployment rate'],['青年失业率','Youth unemployment'],['就业率与参与率','Employment and participation'],['就业增长','Employment growth'],['职位空缺率','Vacancy rate'],['平均与实际工资','Nominal and real wages'],['劳动生产率','Labor productivity'],['非正规就业占比','Informal employment share']] },
  { id: 'households', zh: '居民与生活水平', en: 'Households', indicators: [['可支配收入','Disposable income'],['实际消费','Real consumption'],['家庭储蓄率','Household saving rate'],['家庭债务 / GDP','Household debt / GDP'],['债务偿付率','Debt service ratio'],['房价 / 收入','House price / income'],['收入基尼系数','Income Gini'],['贫困率','Poverty rate']] },
  { id: 'fiscal', zh: '政府财政', en: 'Fiscal', indicators: [['财政收入与支出 / GDP','Revenue and spending / GDP'],['财政余额 / GDP','Fiscal balance / GDP'],['基本财政余额','Primary balance'],['结构性财政余额','Structural balance'],['税收收入 / GDP','Tax revenue / GDP'],['政府投资','Public investment'],['医疗、教育与养老金支出','Health, education and pension spending'],['政府现金余额','Government cash balance']] },
  { id: 'debt', zh: '主权债务', en: 'Sovereign Debt', indicators: [['一般政府总债务 / GDP','Gross general government debt / GDP'],['政府净债务','Government net debt'],['中央与地方政府债务','Central and local debt'],['或有负债与担保','Contingent liabilities and guarantees'],['未来一年再融资需求','One-year refinancing need'],['平均到期期限','Average maturity'],['利息支出 / 财政收入','Interest / revenue'],['外币政府债务占比','Foreign-currency government debt share'],['持有人结构','Holder composition']] },
  { id: 'monetary', zh: '货币政策与央行', en: 'Monetary', indicators: [['政策利率','Policy rate'],['隔夜与回购利率','Overnight and repo rates'],['实际政策利率','Real policy rate'],['M1 / M2 增速','M1 / M2 growth'],['银行准备金','Bank reserves'],['央行资产 / GDP','Central bank assets / GDP'],['量化宽松与缩表','QE and QT'],['汇率制度','Exchange-rate regime']] },
  { id: 'curve', zh: '国债收益率曲线', en: 'Yield Curve', indicators: [['3 月与 6 月国债','3M and 6M bills'],['1、2、3 年期国债','1Y, 2Y and 3Y yields'],['5、7、10 年期国债','5Y, 7Y and 10Y yields'],['20、30、50 年期国债','20Y, 30Y and 50Y yields'],['2 年－10 年利差','2Y–10Y spread'],['3 月－10 年利差','3M–10Y spread'],['通胀保值债实际收益率','Inflation-linked real yield'],['主权信用利差','Sovereign credit spread']] },
  { id: 'banking', zh: '银行与信贷', en: 'Banking', indicators: [['银行信贷 / GDP','Bank credit / GDP'],['贷款与存款增速','Loan and deposit growth'],['不良贷款率','NPL ratio'],['拨备覆盖率','Provision coverage'],['CET1 资本比率','CET1 ratio'],['流动性覆盖率','Liquidity coverage ratio'],['银行净息差','Net interest margin'],['外汇敞口','FX exposure']] },
  { id: 'markets', zh: '金融市场', en: 'Financial Markets', indicators: [['股市总市值 / GDP','Equity market cap / GDP'],['主要股指与估值','Equity indices and valuations'],['企业债收益率','Corporate bond yields'],['投资级与高收益利差','Investment-grade and high-yield spreads'],['房地产价格与租金','Property prices and rents'],['房贷利率','Mortgage rate'],['企业违约率','Corporate default rate'],['主权 CDS','Sovereign CDS']] },
  { id: 'external', zh: '贸易与国际收支', en: 'External', indicators: [['商品与服务贸易余额','Goods and services balance'],['经常账户 / GDP','Current account / GDP'],['初次与二次收入','Primary and secondary income'],['金融账户','Financial account'],['FDI 流入与流出','FDI inflows and outflows'],['证券投资流动','Portfolio flows'],['净误差与遗漏','Net errors and omissions'],['净国际投资头寸 / GDP','NIIP / GDP']] },
  { id: 'fx', zh: '汇率、外储与外债', en: 'FX & Reserves', indicators: [['名义与实际有效汇率','NEER and REER'],['外汇储备与黄金','FX reserves and gold'],['净储备与可用储备','Net and usable reserves'],['进口覆盖月数','Months of import cover'],['储备 / 短期外债','Reserves / short-term external debt'],['总外债 / GDP','Gross external debt / GDP'],['外币债务 / GDP','Foreign-currency debt / GDP'],['未对冲外汇敞口','Unhedged FX exposure'],['央行远期与掉期头寸','Central bank forwards and swaps']] },
  { id: 'corporate', zh: '企业部门', en: 'Corporate', indicators: [['企业利润 / GDP','Corporate profits / GDP'],['企业投资','Corporate investment'],['企业债务 / GDP','Corporate debt / GDP'],['利息保障倍数','Interest coverage'],['债务 / EBITDA','Debt / EBITDA'],['破产与违约率','Insolvency and default rates'],['企业信心','Business confidence'],['制造业 PMI','Manufacturing PMI']] },
  { id: 'demographics', zh: '人口与保障', en: 'Demographics', indicators: [['人口增长率','Population growth'],['劳动年龄人口','Working-age population'],['生育率','Fertility rate'],['中位年龄','Median age'],['老年抚养比','Old-age dependency ratio'],['净移民','Net migration'],['养老金支出 / GDP','Pension spending / GDP'],['养老金资金缺口','Unfunded pension liability']] },
  { id: 'productivity', zh: '生产率与创新', en: 'Productivity & Innovation', indicators: [['每小时劳动产出','Output per hour'],['全要素生产率','Total factor productivity'],['潜在 GDP 增长','Potential GDP growth'],['研发支出 / GDP','R&D / GDP'],['专利与高技术出口','Patents and high-tech exports'],['教育与人力资本','Education and human capital'],['能源强度','Energy intensity'],['碳排放 / GDP','CO₂ / GDP']] },
  { id: 'institutions', zh: '制度与特殊风险', en: 'Institutions & Risk', indicators: [['汇率与资本账户制度','FX and capital-account regime'],['央行独立性','Central bank independence'],['财政规则','Fiscal rules'],['主权信用评级','Sovereign ratings'],['地方融资平台','Local financing vehicles'],['国企与政府担保','State firms and guarantees'],['能源进口依赖','Energy import dependence'],['气候相关财政风险','Climate-related fiscal risk']] },
];
