import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { macroCountries, macroSources } from './macroIndicators';
import { MoreMacroData } from './MoreMacroData';
import { WorldBankData } from './WorldBankData';
import { MacroHistory } from './MacroHistory';

type Locale = 'zh' | 'en';
const fmt = (value: number) => `${value > 0 ? '+' : value < 0 ? '−' : ''}${Math.abs(value).toFixed(1)}%`;

export function MacroRisk({ locale }: { locale: Locale }) {
  const en = locale === 'en';
  const [code, setCode] = useState('US');
  const [openingDebt, setOpeningDebt] = useState(1000);
  const [revenue, setRevenue] = useState(300);
  const [spending, setSpending] = useState(350);
  const [adjustment, setAdjustment] = useState(0);
  const country = macroCountries.find((item) => item.code === code)!;
  const deficit = spending - revenue;
  const closingDebt = openingDebt + deficit + adjustment;
  const items = [
    { n: '01', label: en ? 'Fiscal balance / GDP' : '财政收支 / GDP', value: fmt(country.fiscalBalance), year: 2025, source: macroSources.fiscal, note: en ? 'Negative = deficit; annual flow' : '负数为赤字 · 年度流量' },
    { n: '02', label: en ? 'Gross government debt / GDP' : '政府总债务 / GDP', value: `${country.grossDebt.toFixed(1)}%`, year: 2025, source: macroSources.debt, note: en ? 'General government; stock' : '一般政府 · 债务存量' },
    { n: '03', label: en ? 'Interest / revenue' : '利息支出 / 财政收入', value: country.interestRevenue ? `${country.interestRevenue.value.toFixed(1)}%` : '—', year: country.interestRevenue?.year, source: macroSources.interest, note: country.interestRevenue ? (en ? 'World Bank WDI; check coverage' : '世界银行 WDI · 注意机构口径') : (en ? 'Comparable recent value unavailable' : '近期可比值未取得') },
    { n: '04', label: en ? 'Current account / GDP' : '经常账户 / GDP', value: fmt(country.currentAccount), year: 2025, source: macroSources.current, note: en ? 'Positive = external surplus' : '正数为对外顺差' },
    { n: '05', label: en ? 'Reserves / short-term external debt' : '储备 / 短期外债', value: country.reservesShortDebt ? `${country.reservesShortDebt.value.toFixed(2)}×` : '—', year: country.reservesShortDebt?.year, source: macroSources.reserves, note: country.reservesShortDebt ? (en ? 'Total reserves incl. gold / original-maturity debt' : '总储备含黄金 / 原始期限短债') : (en ? 'No uniform seven-market series' : '暂无七国统一可比序列') },
    { n: '06', label: en ? 'Foreign-currency debt share' : '外币债务占比', value: '—', year: undefined, source: macroSources.currency, note: en ? 'Debtor, sector and currency breakdown needed' : '须指定债务主体、部门与计价币种' },
  ];

  return <>
    <section className="macro-overview" id="macro-risk" aria-labelledby="macro-heading">
      <div className="economy-section-title"><div><span>{en ? 'MACRO RISK / SIX NUMBERS' : '宏观风险 / 六个数字'}</span><h2 id="macro-heading">{en ? 'Beyond bond yields' : '从利率走向国家资产负债表'}</h2></div><p>{en ? 'A country can have a high debt ratio but strong assets, or a modest debt ratio with acute foreign-currency stress. Read the six measures together.' : '债务率高不一定意味着脆弱；债务率低也可能有外币和外部融资风险。六项指标要放在一起看。'}</p></div>
      <div className="macro-country-tabs" role="group" aria-label={en ? 'Choose a country' : '选择国家'}>{macroCountries.map((item) => <button key={item.code} type="button" aria-pressed={code === item.code} className={code === item.code ? 'active' : ''} onClick={() => setCode(item.code)}>{item.flag} {item[locale]}</button>)}</div>
      <div className="macro-current-country"><strong>{country.flag} {country[locale]}</strong><span>{en ? 'Fiscal, debt and current account: IMF WEO April 2026 edition, 2025 observation/estimate. Other series show their own years.' : '财政、债务、经常账户：IMF《世界经济展望》2026 年 4 月版中的 2025 年观察值／估计值；其余指标逐项标年。'}</span></div>
      <div className="macro-metric-grid">{items.map((item) => <article key={item.n}><div className="macro-metric-top"><span>{item.n}</span><a href={item.source} target="_blank" rel="noopener noreferrer" aria-label={`${item.label} ${en ? 'source' : '数据来源'}`}><ArrowUpRight size={15}/></a></div><h3>{item.label}</h3><strong>{item.value}</strong><p>{item.note}</p><small>{item.year ? `${item.year} · ${item.n === '03' || item.n === '05' ? (en ? 'World Bank WDI' : '世界银行 WDI') : 'IMF WEO'} · ${en ? 'annual' : '年度'}` : (en ? 'Comparable series pending' : '可比序列待补')}</small></article>)}</div>
      {code === 'SG' && <p className="macro-country-note">{en ? 'Singapore is a clear example of why gross debt cannot stand alone: its Ministry of Finance says government financial assets exceed its debt, and most borrowing serves non-spending purposes.' : '新加坡是“不能只看总债务率”的典型：其财政部说明，政府金融资产超过债务，多数借款用于非财政支出用途。'} <a href="https://www.mof.gov.sg/policies/reserves/our-assets-and-liabilities/" target="_blank" rel="noopener noreferrer">{en ? 'Singapore MOF' : '新加坡财政部'} ↗</a></p>}
      {code === 'CN' && <p className="macro-country-note">{en ? 'China’s 2.65× figure is calculated as the inverse of the World Bank’s 2024 “short-term debt as % of total reserves” series. It uses reserves including gold and debt by original maturity.' : '中国的 2.65 倍由世界银行 2024 年“短期外债／总储备”倒算；总储备包含黄金，短债按原始期限统计，不能代替未来一年实际到期外币支付压力。'}</p>}
      <p className="macro-caveat">{en ? 'A dash means no recent, sufficiently comparable figure was incorporated here; it is not zero. WDI interest/revenue may use a different institutional boundary from WEO general-government debt. Do not rank countries by these numbers alone.' : '“—”表示本页尚未纳入近期且足够可比的数值，不代表零。世行利息／收入序列与 IMF 一般政府债务可能采用不同机构边界，不宜直接据此给国家排名。'}</p>
      <MoreMacroData locale={locale} code={code} />
      <WorldBankData locale={locale} code={code} />
      <MacroHistory locale={locale} code={code} />
    </section>

    <section className="macro-mechanics" aria-labelledby="debt-heading"><div className="economy-section-title"><div><span>{en ? 'FLOW AND STOCK' : '流量与存量'}</span><h2 id="debt-heading">{en ? 'How a deficit becomes debt' : '财政赤字如何变成政府债务'}</h2></div><p>{en ? 'Change the assumptions. This is a simple accounting illustration, not a country forecast.' : '调整下面的数字，看看赤字与存量如何衔接。这里是会计示意，不是国家预测。'}</p></div><div className="macro-debt-layout"><div className="macro-debt-controls">{[
      { key: 'opening', label: en ? 'Opening debt' : '年初债务', value: openingDebt, setter: setOpeningDebt, min: 0, max: 2000 },
      { key: 'revenue', label: en ? 'Government revenue' : '本年收入', value: revenue, setter: setRevenue, min: 0, max: 700 },
      { key: 'spending', label: en ? 'Government spending' : '本年支出', value: spending, setter: setSpending, min: 0, max: 700 },
      { key: 'adjustment', label: en ? 'Other debt adjustments' : '其他债务调整', value: adjustment, setter: setAdjustment, min: -200, max: 200 },
    ].map((control) => <label key={control.key}><span>{control.label}<b>{control.value}</b></span><input type="range" min={control.min} max={control.max} step="10" value={control.value} onChange={(event) => control.setter(Number(event.target.value))}/></label>)}</div><div className="macro-debt-result"><span>{en ? 'END-OF-YEAR DEBT / APPROX.' : '年末债务 / 粗略估算'}</span><strong>{closingDebt.toLocaleString()}</strong><div className="macro-debt-equation"><span>{openingDebt.toLocaleString()}</span><b>{deficit >= 0 ? '+' : '−'}</b><span>{Math.abs(deficit).toLocaleString()}</span><b>{adjustment >= 0 ? '+' : '−'}</b><span>{Math.abs(adjustment).toLocaleString()}</span></div><p>{en ? `Annual ${deficit >= 0 ? 'deficit' : 'surplus'}: ${Math.abs(deficit)}. Other adjustments can include valuation changes, asset transactions and changes in cash balances.` : `本年${deficit >= 0 ? '赤字' : '盈余'}：${Math.abs(deficit)}。其他调整可包括资产交易、估值变化和现金余额变化。`}</p></div></div><p className="macro-source-note">{en ? 'The difference between the deficit and the change in debt is commonly called a stock-flow adjustment. Use the same government perimeter and accounting basis before comparing.' : '赤字与债务增量之间的差额常称为“存量—流量调整”。比较前必须统一政府部门边界和会计口径。'} <a href="https://www.imf.org/en/publications/wp/issues/2016/12/31/defining-the-governments-debt-and-deficit-43408" target="_blank" rel="noopener noreferrer">IMF ↗</a></p></section>

    <section className="macro-external" aria-labelledby="external-heading"><div className="economy-section-title"><div><span>{en ? 'EXTERNAL POSITION' : '外部账户与外汇压力'}</span><h2 id="external-heading">{en ? 'Where financing crosses borders' : '对外收支、外债与外币风险'}</h2></div></div><div className="macro-external-grid"><article><span>01 / CURRENT ACCOUNT</span><h3>{en ? 'Current account' : '经常账户'}</h3><p>{en ? 'Goods + services + primary income + secondary income. A deficit means the economy needs net external financing; it does not tell you which sector borrowed.' : '货物 + 服务 + 初次收入 + 二次收入。赤字意味着整个经济体需要净对外融资，但不能直接说明是谁借了钱。'}</p><div>{en ? 'Current account = national saving − investment' : '经常账户 = 国内储蓄 − 国内投资'}</div></article><article><span>02 / RESIDENCE VS CURRENCY</span><h3>{en ? 'External is not foreign-currency' : '外债不等于外币债'}</h3><p>{en ? 'External debt is owed by residents to nonresidents, regardless of currency. Foreign-currency debt is defined by denomination, regardless of who holds it.' : '外债看债权人是否为非居民，不看币种；外币债看债务以什么货币计价，不看债权人住在哪里。'}</p><div>{en ? 'CNY owed abroad can be external debt · USD owed at home can be FX debt' : '欠境外人的人民币可能是外债 · 欠本国银行的美元可能是外币债'}</div></article><article><span>03 / LIQUIDITY</span><h3>{en ? 'Reserves are not all spendable cash' : '总外储不是全部可动用现金'}</h3><p>{en ? 'Check short-term external debt and the reserve template’s scheduled and contingent foreign-currency drains, including swaps and guarantees.' : '还要看短期外债，以及储备模板披露的预定和或有外币流出，包括掉期与担保。'}</p><div>{en ? 'Gross reserves → near-term FX obligations → usable liquidity' : '总储备 → 近期外币义务 → 可用流动性'}</div></article></div><div className="macro-external-foot"><p>{en ? 'A wider fiscal deficit can reduce national saving and, other things equal, worsen the current account. Private saving and investment can offset this: “twin deficits” are a pattern to test, not an automatic rule.' : '财政赤字扩大可能降低国民储蓄，其他条件不变时使经常账户恶化。但居民与企业储蓄、投资也会变化；“双赤字”是一种需要检验的关系，不是机械定律。'}</p><a href="https://www.elibrary.imf.org/abstract/book/9781589068124/ch02.xml" target="_blank" rel="noopener noreferrer">{en ? 'IMF balance-of-payments framework' : 'IMF 国际收支框架'} ↗</a></div></section>

    <section className="macro-chain" aria-labelledby="chain-heading"><div className="economy-section-title"><div><span>{en ? 'CRISIS TRANSMISSION' : '风险传导'}</span><h2 id="chain-heading">{en ? 'One possible stress chain' : '一种可能的外汇压力链'}</h2></div><p>{en ? 'This is a scenario, not a prediction. Each link depends on policy, private balance sheets and market access.' : '这是一种分析情景，不是预测；每一步都受政策、私人部门资产负债表和融资渠道影响。'}</p></div><ol>{(en ? ['Persistent fiscal and external financing needs', 'Capital inflows slow or reverse', 'Currency depreciates; reserves may be used', 'Foreign-currency debt service rises in local currency', 'Refinancing and sovereign risk intensify'] : ['财政与对外融资需求持续存在', '资本流入放缓或逆转', '本币贬值，外储可能被动用', '外币债务的本币偿付成本上升', '再融资与主权风险加剧']).map((step, index) => <li key={step}><span>0{index + 1}</span><strong>{step}</strong></li>)}</ol><p>{en ? 'Also inspect contingent liabilities: local-government financing vehicles, state-owned enterprises, guarantees, PPPs, bank rescues and off-balance-sheet commitments may change the picture.' : '还要检查或有负债：地方融资平台、国企、担保、PPP、银行救助和表外承诺，可能改变只看“政府债务率”得出的结论。'}</p></section>
  </>;
}
